# Generated by Django 5.0.3 on 2024-03-19 05:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        default="Unknown", max_length=50, verbose_name="Product Name"
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(
                        default="Unknown", max_length=50, verbose_name="Company Name"
                    ),
                ),
                (
                    "manufacture_location",
                    models.CharField(
                        choices=[
                            ("Abu Dhabi", "Abu Dhabi"),
                            ("Dubai", "Dubai"),
                            ("Ajman", "Ajman"),
                        ],
                        default="Abu Dhabi",
                        max_length=50,
                        verbose_name="Location",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("RC", "Recycable"), ("NRC", "Non Recycable")],
                        default="RC",
                        max_length=50,
                        verbose_name="Product Type",
                    ),
                ),
                (
                    "product_quantity",
                    models.IntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "product_mf_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Manufacturing Date"
                    ),
                ),
                (
                    "product_expiry_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Expiry Date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        default="Unknown", max_length=50, verbose_name="Product Name"
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(
                        default="Unknown", max_length=50, verbose_name="Company Name"
                    ),
                ),
                (
                    "manufacture_location",
                    models.CharField(
                        default="Abu Dhabi", max_length=50, verbose_name="Location"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("RC", "Recycable"), ("NRC", "Non Recycable")],
                        default="RC",
                        max_length=50,
                        verbose_name="Product Type",
                    ),
                ),
                (
                    "product_quantity",
                    models.IntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "product_mf_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Manufacturing Date"
                    ),
                ),
                (
                    "product_expiry_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "product_ownership",
                    models.CharField(
                        choices=[
                            ("MC", "Merchant"),
                            ("CN", "Consumer"),
                            ("US", "User"),
                        ],
                        default="US",
                        max_length=50,
                        verbose_name="Ownership",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.manufacturer",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
